/*
                                **WARNING**


This is an autogenerated Nix file! Do not edit by hand!


Modifications to autogenerated Nix code can be made by running:

  `make autogen-deps`

in the repository root, after completing one or more of the following:

For Purescript dependencies:

  - Edit `spago.dhall`

For JS dependencies:

  - Edit `package.json`
  - Remove the symlinked `node_modules`
  - Run `npm i --package-lock-only`


*/
# This file has been generated by node2nix 1.9.0. Do not edit!

{pkgs ? import <nixpkgs> {
    inherit system;
  }, system ? builtins.currentSystem, nodejs ? pkgs."nodejs-12_x"}:

let
  nodeEnv = import ./node-env.nix {
    inherit (pkgs) stdenv lib python2 runCommand writeTextFile;
    inherit pkgs nodejs;
    libtool = if pkgs.stdenv.isDarwin then pkgs.darwin.cctools else null;
  };
in
import ./node-packages.nix {
  inherit (pkgs) fetchurl nix-gitignore stdenv lib fetchgit;
  inherit nodeEnv;
}
