# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@cardano-ogmios/client-4.2.1" = {
      name = "_at_cardano-ogmios_slash_client";
      packageName = "@cardano-ogmios/client";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cardano-ogmios/client/-/client-4.2.1.tgz";
        sha512 = "CiScFBqOeMZtFLN67jUqsiad4xIoW17TIt+QfZlgpX5nTHHjs1kTuoNYN088dICrBy7M6EvkETQBJLwK/BR83Q==";
      };
    };
    "@cardano-ogmios/schema-4.2.1" = {
      name = "_at_cardano-ogmios_slash_schema";
      packageName = "@cardano-ogmios/schema";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cardano-ogmios/schema/-/schema-4.2.1.tgz";
        sha512 = "XRiew+YFeat/cfXAdjwWXux+agRGA5SzD0VCYXnZ9OtxgjyApwXxpbGFLeGxuz7FyMlAKimS88fq37dJPacS1Q==";
      };
    };
    "@cardanosolutions/json-bigint-1.0.0" = {
      name = "_at_cardanosolutions_slash_json-bigint";
      packageName = "@cardanosolutions/json-bigint";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cardanosolutions/json-bigint/-/json-bigint-1.0.0.tgz";
        sha512 = "46ts2s0W63nzqHMhaXKACeY0GDWdnPet9wqOWtb8X3Y5LzokcaDKupLO2eHUwlvQyFzD9gxJlWPi/LqZPkn4oQ==";
      };
    };
    "@emurgo/cardano-serialization-lib-nodejs-9.1.4" = {
      name = "_at_emurgo_slash_cardano-serialization-lib-nodejs";
      packageName = "@emurgo/cardano-serialization-lib-nodejs";
      version = "9.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emurgo/cardano-serialization-lib-nodejs/-/cardano-serialization-lib-nodejs-9.1.4.tgz";
        sha512 = "zDYQ4E5CAz89OuXCPV7k3v5kLWkwUS5Jg7QZ5m/4vPkeuZolOXyqo84p6AYf0qZ14xkgxnvHIRY+heJKNs7Ddw==";
      };
    };
    "@types/json-bigint-1.0.1" = {
      name = "_at_types_slash_json-bigint";
      packageName = "@types/json-bigint";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/json-bigint/-/json-bigint-1.0.1.tgz";
        sha512 = "zpchZLNsNuzJHi6v64UBoFWAvQlPhch7XAi36FkH6tL1bbbmimIF+cS7vwkzY4u5RaSWMoflQfu+TshMPPw8uw==";
      };
    };
    "bech32-2.0.0" = {
      name = "bech32";
      packageName = "bech32";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bech32/-/bech32-2.0.0.tgz";
        sha512 = "LcknSilhIGatDAsY1ak2I8VtGaHNhgMSYVxFrGLXv+xLHytaKZKcaUJJUE7qmBr7h33o5YQwP55pMI0xmkpJwg==";
      };
    };
    "big-integer-1.6.51" = {
      name = "big-integer";
      packageName = "big-integer";
      version = "1.6.51";
      src = fetchurl {
        url = "https://registry.npmjs.org/big-integer/-/big-integer-1.6.51.tgz";
        sha512 = "GPEid2Y9QU1Exl1rpO9B2IPJGHPSupF5GnVIP0blYvNOMer2bTvSWs1jGOUg04hTmu67nmLsQ9TBo1puaotBHg==";
      };
    };
    "bignumber.js-9.0.2" = {
      name = "bignumber.js";
      packageName = "bignumber.js";
      version = "9.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bignumber.js/-/bignumber.js-9.0.2.tgz";
        sha512 = "GAcQvbpsM0pUb0zw1EI0KhQEZ+lRwR5fYaAp3vPOYuP7aDvGy6cVN6XHLauvF8SOga2y0dcLcjt3iQDTSEliyw==";
      };
    };
    "bufferutil-4.0.5" = {
      name = "bufferutil";
      packageName = "bufferutil";
      version = "4.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/bufferutil/-/bufferutil-4.0.5.tgz";
        sha512 = "HTm14iMQKK2FjFLRTM5lAVcyaUzOnqbPtesFIvREgXpJHdQm8bWS+GkQgIkfaBYRHuCnea7w8UVNfwiAQhlr9A==";
      };
    };
    "cross-fetch-3.1.4" = {
      name = "cross-fetch";
      packageName = "cross-fetch";
      version = "3.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-fetch/-/cross-fetch-3.1.4.tgz";
        sha512 = "1eAtFWdIubi6T4XPy6ei9iUFoKpUkIF971QLN8lIvvvwueI65+Nw5haMNKUwfJxabqlIIDODJKGrQ66gxC0PbQ==";
      };
    };
    "fastq-1.13.0" = {
      name = "fastq";
      packageName = "fastq";
      version = "1.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fastq/-/fastq-1.13.0.tgz";
        sha512 = "YpkpUnK8od0o1hmeSc7UUs/eB/vIPWJYjKck2QKIzAf71Vm1AAQ3EbuZB3g2JIy+pg+ERD0vqI79KyZiB2e2Nw==";
      };
    };
    "isomorphic-ws-4.0.1" = {
      name = "isomorphic-ws";
      packageName = "isomorphic-ws";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isomorphic-ws/-/isomorphic-ws-4.0.1.tgz";
        sha512 = "BhBvN2MBpWTaSHdWRb/bwdZJ1WaehQ2L1KngkCkfLUGF0mAWAT1sQUQacEmQ0jXkFw/czDXPNQSL5u2/Krsz1w==";
      };
    };
    "nanoid-3.1.30" = {
      name = "nanoid";
      packageName = "nanoid";
      version = "3.1.30";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoid/-/nanoid-3.1.30.tgz";
        sha512 = "zJpuPDwOv8D2zq2WRoMe1HsfZthVewpel9CAvTfc/2mBD1uUT/agc5f7GHGWXlYkFvi1mVxe4IjvP2HNrop7nQ==";
      };
    };
    "node-fetch-2.6.1" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "2.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-2.6.1.tgz";
        sha512 = "V4aYg89jEoVRxRb2fJdAg8FHvI7cEyYdVAh94HH0UIK8oJxUfkjlDQN9RbMx+bEjP7+ggMiFRprSti032Oipxw==";
      };
    };
    "node-gyp-build-4.3.0" = {
      name = "node-gyp-build";
      packageName = "node-gyp-build";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-gyp-build/-/node-gyp-build-4.3.0.tgz";
        sha512 = "iWjXZvmboq0ja1pUGULQBexmxq8CV4xBhX7VDOTbL7ZR4FOowwY/VOtRxBN/yKxmdGoIp4j5ysNT4u3S2pDQ3Q==";
      };
    };
    "reusify-1.0.4" = {
      name = "reusify";
      packageName = "reusify";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/reusify/-/reusify-1.0.4.tgz";
        sha512 = "U9nH88a3fc/ekCF1l0/UP1IosiuIjyTh7hBvXVMHYgVcfGvt897Xguj2UOLDeI5BG2m7/uwyaLVT6fbtCwTyzw==";
      };
    };
    "ts-custom-error-3.2.0" = {
      name = "ts-custom-error";
      packageName = "ts-custom-error";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ts-custom-error/-/ts-custom-error-3.2.0.tgz";
        sha512 = "cBvC2QjtvJ9JfWLvstVnI45Y46Y5dMxIaG1TDMGAD/R87hpvqFL+7LhvUDhnRCfOnx/xitollFWWvUKKKhbN0A==";
      };
    };
    "uniqid-5.4.0" = {
      name = "uniqid";
      packageName = "uniqid";
      version = "5.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uniqid/-/uniqid-5.4.0.tgz";
        sha512 = "38JRbJ4Fj94VmnC7G/J/5n5SC7Ab46OM5iNtSstB/ko3l1b5g7ALt4qzHFgGciFkyiRNtDXtLNb+VsxtMSE77A==";
      };
    };
    "ws-7.5.6" = {
      name = "ws";
      packageName = "ws";
      version = "7.5.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-7.5.6.tgz";
        sha512 = "6GLgCqo2cy2A2rjCNFlxQS6ZljG/coZfZXclldI8FB/1G3CCI36Zd8xy2HrFVACi8tfk5XrgLQEk+P0Tnz9UcA==";
      };
    };
    "ws-8.4.0" = {
      name = "ws";
      packageName = "ws";
      version = "8.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-8.4.0.tgz";
        sha512 = "IHVsKe2pjajSUIl4KYMQOdlyliovpEPquKkqbwswulszzI7r0SfQrxnXdWAEqOlDCLrVSJzo+O1hAwdog2sKSQ==";
      };
    };
  };
  args = {
    name = "realpab";
    packageName = "realpab";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      (sources."@cardano-ogmios/client-4.2.1" // {
        dependencies = [
          sources."@cardano-ogmios/schema-4.2.1"
          sources."@cardanosolutions/json-bigint-1.0.0"
          sources."@types/json-bigint-1.0.1"
          sources."bignumber.js-9.0.2"
          sources."cross-fetch-3.1.4"
          sources."fastq-1.13.0"
          sources."isomorphic-ws-4.0.1"
          sources."nanoid-3.1.30"
          sources."node-fetch-2.6.1"
          sources."reusify-1.0.4"
          sources."ts-custom-error-3.2.0"
          sources."ws-7.5.6"
        ];
      })
      sources."@emurgo/cardano-serialization-lib-nodejs-9.1.4"
      sources."bech32-2.0.0"
      sources."big-integer-1.6.51"
      (sources."bufferutil-4.0.5" // {
        dependencies = [
          sources."node-gyp-build-4.3.0"
        ];
      })
      sources."uniqid-5.4.0"
      sources."ws-8.4.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "";
      license = "ISC";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
