let upstream =
    -- https://github.com/mlabs-haskell/purescript-cardano-package-set
      https://raw.githubusercontent.com/mlabs-haskell/purescript-cardano-package-set/v4.2.0/packages.dhall
        sha256:03c0bc2f30b7c1bf4dd01d5a94515223fc755d0269e30780523ac67bc19ffa00

let additions = 
      { cardano-provider =
        { dependencies =
          [ "aeson"
          , "aff"
          , "aff-promise"
          , "affjax"
          , "argonaut-codecs"
          , "arrays"
          , "bifunctors"
          , "cardano-types"
          , "effect"
          , "either"
          , "exceptions"
          , "foldable-traversable"
          , "lists"
          , "maybe"
          , "newtype"
          , "ordered-collections"
          , "prelude"
          , "strings"
          , "these"
          , "tuples"
          , "uint"
          ]
        , repo = "https://github.com/mlabs-haskell/purescript-cardano-provider"
        , version = "031075c0d56536ee3e459b5207c9f50487f605b0"
        }
      , cardano-blockfrost-provider =
        { dependencies =
          [ "aeson"
          , "aff"
          , "affjax"
          , "arrays"
          , "bifunctors"
          , "bignumber"
          , "bytearrays"
          , "cardano-data-lite"
          , "cardano-provider"
          , "cardano-types"
          , "console"
          , "datetime"
          , "effect"
          , "either"
          , "exceptions"
          , "foldable-traversable"
          , "foreign-object"
          , "http-methods"
          , "js-bigints"
          , "js-date"
          , "maybe"
          , "media-types"
          , "monad-logger"
          , "newtype"
          , "node-process"
          , "numbers"
          , "ordered-collections"
          , "parallel"
          , "partial"
          , "prelude"
          , "strings"
          , "transformers"
          , "tuples"
          , "uint"
          ]
        , repo =
            "https://github.com/mlabs-haskell/purescript-cardano-blockfrost-provider"
        , version = "1f4682b629207b4af641aa5abb2242eb0c416b67"
        }
      , cardano-kupmios-provider =
        { dependencies =
          [ "aeson"
          , "aff"
          , "affjax"
          , "arrays"
          , "bifunctors"
          , "bytearrays"
          , "cardano-provider"
          , "cardano-data-lite"
          , "cardano-types"
          , "concurrent-queues"
          , "console"
          , "control"
          , "datetime"
          , "effect"
          , "either"
          , "exceptions"
          , "foldable-traversable"
          , "foreign-object"
          , "formatters"
          , "http-methods"
          , "integers"
          , "js-bigints"
          , "js-date"
          , "maybe"
          , "monad-logger"
          , "newtype"
          , "node-process"
          , "ordered-collections"
          , "parallel"
          , "partial"
          , "prelude"
          , "profunctor-lenses"
          , "record"
          , "strings"
          , "stringutils"
          , "tailrec"
          , "transformers"
          , "tuples"
          , "uint"
          , "untagged-union"
          ]
        , repo =
            "https://github.com/mlabs-haskell/purescript-cardano-kupmios-provider"
        , version = "aede2b484d76e335dd1bfcf76acc116be94cdd12"
        }
      }

in (upstream // additions)
