let upstream =
    -- https://github.com/mlabs-haskell/purescript-cardano-package-set
      https://raw.githubusercontent.com/mlabs-haskell/purescript-cardano-package-set/v4.2.0/packages.dhall
        sha256:03c0bc2f30b7c1bf4dd01d5a94515223fc755d0269e30780523ac67bc19ffa00

let additions = 
      { cardano-provider =
        { dependencies =
          [ "aeson"
          , "aff"
          , "aff-promise"
          , "affjax"
          , "argonaut-codecs"
          , "arrays"
          , "bifunctors"
          , "cardano-types"
          , "effect"
          , "either"
          , "exceptions"
          , "foldable-traversable"
          , "lists"
          , "maybe"
          , "newtype"
          , "ordered-collections"
          , "prelude"
          , "strings"
          , "these"
          , "tuples"
          , "uint"
          ]
        , repo = "https://github.com/mlabs-haskell/purescript-cardano-provider"
        , version = "031075c0d56536ee3e459b5207c9f50487f605b0"
        }
      , cardano-blockfrost-provider =
        { dependencies =
          [ "aeson"
          , "aff"
          , "affjax"
          , "arrays"
          , "bifunctors"
          , "bignumber"
          , "bytearrays"
          , "cardano-data-lite"
          , "cardano-provider"
          , "cardano-types"
          , "console"
          , "datetime"
          , "effect"
          , "either"
          , "exceptions"
          , "foldable-traversable"
          , "foreign-object"
          , "http-methods"
          , "js-bigints"
          , "js-date"
          , "maybe"
          , "media-types"
          , "monad-logger"
          , "newtype"
          , "node-process"
          , "numbers"
          , "ordered-collections"
          , "parallel"
          , "partial"
          , "prelude"
          , "strings"
          , "transformers"
          , "tuples"
          , "uint"
          ]
        , repo =
            "https://github.com/mlabs-haskell/purescript-cardano-blockfrost-provider"
        , version = "e056a3abe841d208cbd0deadb72b58227f68676b"
        }
      , cardano-kupmios-provider =
        { dependencies =
          [ "aeson"
          , "aff"
          , "affjax"
          , "arrays"
          , "bifunctors"
          , "bytearrays"
          , "cardano-provider"
          , "cardano-data-lite"
          , "cardano-types"
          , "concurrent-queues"
          , "console"
          , "control"
          , "datetime"
          , "effect"
          , "either"
          , "exceptions"
          , "foldable-traversable"
          , "foreign-object"
          , "formatters"
          , "http-methods"
          , "integers"
          , "js-bigints"
          , "js-date"
          , "maybe"
          , "monad-logger"
          , "newtype"
          , "node-process"
          , "ordered-collections"
          , "parallel"
          , "partial"
          , "prelude"
          , "profunctor-lenses"
          , "record"
          , "strings"
          , "stringutils"
          , "tailrec"
          , "transformers"
          , "tuples"
          , "uint"
          , "untagged-union"
          ]
        , repo =
            "https://github.com/mlabs-haskell/purescript-cardano-kupmios-provider"
        , version = "26795bd5d29520c37b139b586ef7ae24a708f19b"
        }
      , cardano-types =
        { dependencies =
          [ "aeson"
          , "aff"
          , "arraybuffer-types"
          , "arrays"
          , "bifunctors"
          , "bytearrays"
          , "cardano-plutus-data-schema"
          , "cardano-data-lite"
          , "control"
          , "datetime"
          , "effect"
          , "either"
          , "encoding"
          , "exceptions"
          , "foldable-traversable"
          , "foreign-object"
          , "integers"
          , "js-bigints"
          , "lattice"
          , "lists"
          , "literals"
          , "maybe"
          , "monad-logger"
          , "mote"
          , "mote-testplan"
          , "newtype"
          , "nonempty"
          , "nullable"
          , "ordered-collections"
          , "partial"
          , "prelude"
          , "profunctor"
          , "profunctor-lenses"
          , "quickcheck"
          , "rationals"
          , "record"
          , "safe-coerce"
          , "spec"
          , "these"
          , "tuples"
          , "typelevel-prelude"
          , "uint"
          , "unfoldable"
          , "unsafe-coerce"
          ]
        , repo = "https://github.com/mlabs-haskell/purescript-cardano-types.git"
        , version = "27e07553aaf2ec0d7b58a83623171fa9c8c292c7"
        }
      }

in (upstream // additions)
